### ISSUE TITLE
Beachmark for RSA circuit

### ISSUE THREAD

**Issue by vuvoth** [privacy-scaling-explorations/anon-aadhaar#16]

**Comment by aguzmant103** [comment]
@vuvoth is the intention here to benchmark different implementations of RSA circuit?

**Comment by vuvoth** [comment]
Thank FYI! I think I will benchmark all of them.

**Comment by vuvoth** [comment]
I finished benchmark [here](https://github.com/vuvoth/zk-Harness/tree/rsa-pkcs1-v15-signature-benchmark).
