### ISSUE TITLE
Extract Cert from PDF

### ISSUE THREAD

**Issue by vuvoth** [privacy-scaling-explorations/anon-aadhaar#36]

**Comment by Meyanis95** [comment]
This is needed so the end user don't need to handle .cer files on his phone, which can be impossible on IOS.

**Comment by Meyanis95** [comment]
For this issue we have 2 potentials solutions:

Hardcoded RSA Public Key: We can hardcode the Aadhaar RSA public key into the application to bypass the need for certificate files.

OR

Certificate Extraction: Alternatively, we can extract the necessary certificate information directly from the Aadhaar PDF itself, eliminating the need for external certificate files.

We'll first try to extract the cert from pdf during a 2 weeks sprint and if it's not successful, we can hardcode the RSA public key.

**Comment by Meyanis95** [comment]
I figured out how to extract the certificate from the decrypted pdf only, the issue now is that we need to find a way to decrypt the pdf with the password in a browser.

**Comment by vuvoth** [comment]
I think [this lib](https://github.com/Ausinero33/decrypt-pdf-stream) is useful in our case.
@Meyanis95
