### ISSUE TITLE
Proof is not working anymore

### ISSUE THREAD

**Issue by dipanshuhappy** [privacy-scaling-explorations/anon-aadhaar#89]
# What is the bug? 
Proof is not being created , trapped in error

# How can it be reproduced? (optional) 
Simple try logging in with Aadhar 

# Additional context (optional) 
This is the error Uncaught (in promise) Error: Not all inputs have been set. Only 96 out of 97

and i think its become zkey json was changed

**Comment by dipanshuhappy** [comment]
@Meyanis95  can you check , what issue it could be ?

**Comment by dipanshuhappy** [comment]
It's not working in the example website too

**Comment by Meyanis95** [comment]
Hey @dipanshuhappy 

Yes, we just released a new version of the protocol today and updated the artifacts.
Can you tell me what packages are you using and their version? 
Also, can you update the packages to version 0.1.8 and test again?

**Comment by dipanshuhappy** [comment]
> Hey @dipanshuhappy 
> 
> Yes, we just released a new version of the protocol today and updated the artifacts.
> Can you tell me what packages are you using and their version? 
> Also, can you update the packages to version 0.1.8 and test again? 

I updated to 0.1.8 and got the error  witness.app_id is not defined

**Comment by dipanshuhappy** [comment]
@Meyanis95  you can check the example website , it too doesn't seem to work

**Comment by Meyanis95** [comment]
Are you using the `anon-aadhaar-react` package or just the `anon-aadhaar-pcd` package? 

The proving changed since the `v0.1.8`, now you need to instantiate an `application_id` that will be needed as input to compute the witness.

Let me know which package you're using and I can help you solve this.

Also, yes we are aware of the application app, a fix should be pushed today.

**Comment by dipanshuhappy** [comment]
> Are you using the `anon-aadhaar-react` package or just the `anon-aadhaar-pcd` package? 
> 
> The proving changed since the `v0.1.8`, now you need to instantiate an `application_id` that will be needed as input to compute the witness.
> 
> Let me know which package you're using and I can help you solve this.
> 
> Also, yes we are aware of the application app, a fix should be pushed today.

I am using both in my application with version 0.1.8 

How do I pass the application I'd? In the react one ?

**Comment by Meyanis95** [comment]
I just redeployed the example app and it's should be working.

I suggest you to clear your browser and cached data et test again.

Let me know if it's working.

**Comment by dipanshuhappy** [comment]
@Meyanis95 
Hey i did all you said , but still witness app_id is undefined , i am not sure where i am supposed to define that , i cleared my cache too 

can you once check this repo , about it https://github.com/dipanshuhappy/anon-aadhaar-icp

**Comment by Meyanis95** [comment]
I see that you forked the example-app, have you tried to pull the example app?

**Comment by dipanshuhappy** [comment]
> I see that you forked the example-app, have you tried to pull the example app?

Got it I just recloned and typed ...my code ...thanks for the help... by the way I am implementing anon aadhar on the ICP with integration to Internet identity

**Comment by Meyanis95** [comment]
Great to hear! 
I'm closing this ticket as it's resolved.
